[toolchain]
channel = "1.93.0"
components = [
  "clippy-preview",
  "rust-analyzer",
  "rust-docs",
  "rust-src",
  "rust-std",
  "rustfmt-preview",
]
targets = [
  "wasm32-unknown-unknown",
  "x86_64-unknown-linux-gnu",
]
profile = "default"
