name: Conventional Commit Validation

on:
  push:
    branches:
      - "feature/**"
      - "bugfix/**"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited

jobs:
  build:
    name: Conventional Commit Validation
    runs-on: self-hosted
    steps:
      - name: Skip Duplicate Actions
        id: skip_check
        uses: fkirc/skip-duplicate-actions@v5.3.1
      - if: steps.skip_check.outputs.should_skip != 'true'
        uses: actions/checkout@v3
      - if: steps.skip_check.outputs.should_skip != 'true'
        uses: webiny/action-conventional-commits@v1.3.1
        with:
          allowed-commit-types: "a11y,add,animation,auth,build,business,change,comment,concur,contributor,chore,ci,crit,data,dead,deploy,deprecate,devx,docs,downgrade,easter,experiment,extern,feat,fix,flag,generate,handle,health,holdmy,i18n,ignore,init,license,lint,logging,merge,metrics,mock,move,pass,perf,refactor,remove,revert,safety,secret,seo,style,test,type,typo,ui,upgrade"
